name: Test Ping

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print Time
        run: date
      - name: Curl
        run: curl -s https://your-app.onrender.com/health || true
