name: Render Wake Up (Test)

on:
  schedule:
    - cron: "30 20 * * *" 
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl --retry 3 --retry-delay 30 --max-time 30 https://mealsphere.onrender.com/
